sudo: false
language: node_js
node_js:
  - "stable"
before_script:
  - NODE_ENV=test npx sequelize db:migrate
  - NODE_ENV=test npx sequelize db:seed:all
script:
  - npm test
after_success:
  - npm run coverage
cache:
  directories:
    - node_modules
after_success:
  - npm run coverage
services:
  - postgresql
