sudo: false
language: node_js
node_js:
  - "stable"
before_script:
  - NODE_ENV=test npx sequelize db:migrate
  - rm -rf node_modules/bcrypt
  - npm install -g node-gyp
  - npm i
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
script:
  - npm test
after_success:
  - npm run coverage
cache:
  directories:
    - node_modules
after_success:
  - npm run coverage
services:
  - postgresql