sudo: false
language: node_js
node_js:
  - "10.15"
before_script:
  - NODE_ENV=test npx sequelize db:migrate
  - npm i
script:
  - npm test
after_success:
  - npm run coverage
cache:
  directories:
    - node_modules
services:
  - postgresql
